spring.application.name=plazoleta-ms
server.port=8082

spring.datasource.url=jdbc:h2:mem:plazoletadb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true

usuarios.service.url=http://localhost:8081/api/v1